// <auto-generated />
using System;
using LudoGameEngine.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace LudoGameEngine.Migrations
{
    [DbContext(typeof(LudoContext))]
    partial class LudoContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("LudoGameEngine.Game", b =>
                {
                    b.Property<int>("GameID")
                        .HasColumnType("int");

                    b.Property<DateTime>("EndTimeOfGame")
                        .HasColumnType("datetime2");

                    b.Property<int?>("NextPlayerID")
                        .HasColumnType("int");

                    b.Property<int?>("WinnerPlayerID")
                        .HasColumnType("int");

                    b.HasKey("GameID");

                    b.ToTable("Game");
                });

            modelBuilder.Entity("LudoGameEngine.GamePiece", b =>
                {
                    b.Property<int>("GamePieceID")
                        .HasColumnType("int");

                    b.Property<int>("BoardPosition")
                        .HasColumnType("int");

                    b.Property<int>("PlayerID")
                        .HasColumnType("int");

                    b.Property<int>("StepCounter")
                        .HasColumnType("int");

                    b.Property<int>("positionType")
                        .HasColumnType("int");

                    b.HasKey("GamePieceID");

                    b.HasIndex("PlayerID");

                    b.ToTable("GamePiece");
                });

            modelBuilder.Entity("LudoGameEngine.Player", b =>
                {
                    b.Property<int>("PlayerID")
                        .HasColumnType("int");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("GameID")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<int>("Score")
                        .HasColumnType("int");

                    b.HasKey("PlayerID");

                    b.HasIndex("GameID");

                    b.ToTable("Player");
                });

            modelBuilder.Entity("LudoGameEngine.GamePiece", b =>
                {
                    b.HasOne("LudoGameEngine.Player", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LudoGameEngine.Player", b =>
                {
                    b.HasOne("LudoGameEngine.Game", null)
                        .WithMany("Players")
                        .HasForeignKey("GameID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
